---
Name: crazyeggconfig
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\CrazyEgg\CrazyEggMiddleware:
    properties:
      TagProvider: '%$SilverStripe\CrazyEgg\TagProvider'
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        CrazyEggMiddleware: '%$SilverStripe\CrazyEgg\CrazyEggMiddleware'
