---
Name: crazyeggconfig
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\CrazyEgg\RequestFilter:
    properties:
      TagProvider: %$SilverStripe\CrazyEgg\TagProvider
  SilverStripe\Control\RequestProcessor:
    properties:
      filters:
        - '%$SilverStripe\CrazyEgg\RequestFilter'
